spring:
  profiles:
    active: prod
    include: jwt
  datasource:
    username: <db_username>
    password: <db_password>
    url: jdbc:postgresql://localhost:5432/<db_name>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: <ssl_password>
    key-store-type: PKCS12
  port: 8443
  servlet:
    context-path: /

file-save-path: <path>
windows-drive: <drive>